//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptocurrencyValuePredictorAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRCO304_EXCHANGERATE
    {
        public string CURRENCY_ID { get; set; }
        public System.DateTime DATETIME { get; set; }
        public decimal DOLLAR_VALUE { get; set; }
        public Nullable<decimal> GROWTH { get; set; }
        public Nullable<decimal> GOFAI_NEXT_GROWTH { get; set; }
        public Nullable<decimal> NEURALNETWORK_NEXT_GROWTH { get; set; }
        public string LAST_GDAXTRADE { get; set; }
    }
}
