//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptocurrencyValuePredictorAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRCO304_EXCHANGERATE
    {
        public string currency_id { get; set; }
        public System.DateTime timestamp { get; set; }
        public decimal value { get; set; }
        public Nullable<decimal> growth { get; set; }
        public Nullable<decimal> gofaiNextGrowth { get; set; }
        public Nullable<decimal> neuralNetworkNextGrowth { get; set; }
        public Nullable<int> lastTrade { get; set; }
    }
}
