//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptocurrencyPredictorAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("PRCO304_EXCHANGERATE")]
    public partial class PRCO304_EXCHANGERATE
    {
        [Key]
        [Column(Order = 0)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public string currency_id { get; set; }
        [Key]
        [Column(Order = 1)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public System.DateTime timestamp { get; set; }
        public decimal value { get; set; }
        public Nullable<decimal> growth { get; set; }
        public Nullable<decimal> gofaiNextGrowth { get; set; }
        public Nullable<decimal> neuralNetworkNextGrowth { get; set; }
        public decimal lastTrade { get; set; }
    }
}
